### ISSUE TITLE
feat: JSDoc 환경 세팅, 배포 및 불필요한 주석 제거

### ISSUE THREAD

**Issue by Cheol-Cheol** [kfmp/gitest#22]
## 설명
> JSDoc 환경 세팅, 배포 및 불필요한 주석 제거

## TO-DO
- [x] JSDoc 라이브러리 설치
- [x] GitHub Pages를 활용하여 JSDoc 문서 배포
- [x] JSDoc 관련 주석을 제외한 불필요한 주석 제거

## 기타(참고, 스크린샷 등등)
> 
![image](https://github.com/user-attachments/assets/dd47d7c1-87db-4d55-ae92-62ef1270f987)
